### ISSUE TITLE
Track time spent on each task

### ISSUE THREAD

**Issue by michael-james** [creativecolab/CommunityCrit#110]
As a researcher, I want to know how long each task was on the screen and how much of that time was spent composing a response.

Acceptance criteria:
- [x] track overall time in milliseconds
- [x] track time spent typing or time spent with the input boxes in focus
- [x] store these two data points in the task_history table (add columns "time_overall" and "time_typing" and store through functions in Idea Controller, Link Controller, and Task Controller)

**Comment by reggiewumo** [comment]
f8509a3
04d1c30
