### ISSUE TITLE
Add UI elements for image uploading

### ISSUE THREAD

**Issue by michael-james** [creativecolab/CommunityCrit#234]
As a user, I want to upload images when I submit an idea. They may be sketches or pictures of similar things. If I upload multiple images, I want to select which one to feature.

Acceptance criteria:
- [x] choose a file button
- [x] after a file is selected, show truncated name of file
- [ ] button for adding another attachment
- [ ] way to select which image is featured (radio buttons?)

**Comment by reggiewumo** [comment]
https://github.com/creativecolab/CommunityCrit/tree/image-upload
--single image upload functionality
