### ISSUE TITLE
Control distribution of idea display

### ISSUE THREAD

**Issue by michael-james** [creativecolab/CommunityCrit#254]
When a user goes to the Do An Activity page, show three ideas for them to pick from. One with very little participation, one with medium participation, and one with great participation. Show them in a random order. When the page is refreshed, pick three different ideas from each of these categories. Do not repeat previously shown ideas until all ideas have been viewed.

**Comment by reggiewumo** [comment]
* if number of ideas is not a perfect multiple of 3, 1 or 2 ideas will be repeated before all ideas viewed.
