### ISSUE TITLE
Pre-survey

### ISSUE THREAD

**Issue by josephnle** [creativecolab/CommunityCrit#5]
Users must fill out a survey after registering with the system.

- Survey data must be stored for later analysis
- Survey data may be used for recommendation engine later
- Survey data may be used for condition sorting later
- Users should not be able to proceed to viewing tasks and leaving feedback until they've completed their survey

Questions:
- What questions will be asked? What answers can users choose from?

**Comment by michael-james** [comment]
[Survey Text](https://docs.google.com/document/d/1ovt0VyhoMjmMfqEdjPr9ARbn0IMd7MMxxqI4EsOdm8g/edit)
